trigger:
  - main

pool:
  name: Default

variables:
  GH_TOKEN: $(GH_TOKEN)

steps:
  - script: |
      echo "##vso[task.setvariable variable=GH_TOKEN]$GH_TOKEN"
      python --version
      pip install --upgrade pip
      pip install -r requirements.txt
    env:
      GH_TOKEN: $(GH_TOKEN)
    displayName: 'Install dependencies'

  - script: |
      python -m pytest --junitxml=test-results.xml || true
    displayName: 'Run tests'
    continueOnError: true

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'test-results.xml'
      testRunTitle: 'Python Tests'
    condition: succeededOrFailed()
