trigger:
  - main

pool:
  name: Default   # This specifies that the job will run on the self-hosted agent pool named 'Default'
  demands: []      # You can leave this empty, or specify demands if you need certain conditions

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python -m pytest --junitxml=test-results.xml || true
    displayName: 'Run tests'
    continueOnError: true

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'test-results.xml'
      testRunTitle: 'Python Tests'
    condition: succeededOrFailed()
