trigger:
- main

pool:
  name: Default

steps:
- script: |
    "C:\Users\cavin\AppData\Local\Programs\Python\Python38\python.exe" -m pip install --upgrade pip
    "C:\Users\cavin\AppData\Local\Programs\Python\Python38\python.exe" -m pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    "C:\Users\cavin\AppData\Local\Programs\Python\Python38\python.exe" app.py
  displayName: 'Run Flask App'
