trigger:
- main

pool:
  name: Default

steps:
- script: |
    python -m pip install --upgrade pip
    python -m pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python app.py
  displayName: 'Run Flask App'
