trigger:
- main

pool:
  name: Default

steps:
- script: '"C:\Python38\python.exe" -m pip install --upgrade pip'
  displayName: 'Upgrade pip'

- script: '"C:\Python38\python.exe" -m pip install -r requirements.txt'
  displayName: 'Install dependencies'

- script: '"C:\Python38\python.exe" app.py & timeout /t 10'
  displayName: 'Run Flask App (40 sec preview)'
