trigger:
     - main

     pool:
       vmImage: 'ubuntu-latest'

     steps:
     - task: UsePythonVersion@0
       inputs:
         versionSpec: '3.8'
         addToPath: true

     - script: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
       displayName: 'Install dependencies'

     - script: |
         python -m pytest --junitxml=test-results.xml || true
       displayName: 'Run tests'
       continueOnError: true

     - task: PublishTestResults@2
       inputs:
         testResultsFiles: 'test-results.xml'
         testRunTitle: 'Python Tests'
       condition: succeededOrFailed()